### ISSUE TITLE
Invalid US-ASCII character "\xE2"

### ISSUE THREAD

**Issue by dalanmiller** [jekyll/jekyll#4268]
There's quite a few pages on the Internet talking about this problem with Ruby but none of the solutions seem to work with Jekyll. Ultimately, I'm trying to build a Jekyll site in a Docker container and I've tried setting `@charset` as well as all the `locale` ENV variables. is there something I can set in `_config.yml` to solve this? 

```
Configuration file: /www/_config.yml
            Source: /www
       Destination: /www/_site
 Incremental build: enabled
      Generating...
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/styles.scss':
                    Invalid US-ASCII character "\xE2" on line 3
/usr/local/bundle/gems/jekyll-sass-converter-1.3.0/lib/jekyll/converters/scss.rb:97:in `rescue in convert': Invalid US-ASCII character "\xE2" on line 3 (Jekyll::Converters::Scss::SyntaxError)
	from /usr/local/bundle/gems/jekyll-sass-converter-1.3.0/lib/jekyll/converters/scss.rb:95:in `convert'
	from /usr/local/bundle/bundler/gems/jekyll-43a28aed967b/lib/jekyll/convertible.rb:67:in `block in transform'
	from /usr/local/bundle/bundler/gems/jekyll-43a28aed967b/lib/jekyll/convertible.rb:65:in `each'
	from /usr/local/bundle/bundler/gems/jekyll-43a28aed967b/lib/jekyll/convertible.rb:65:in `reduce'
	from /usr/local/bundle/bundler/gems/jekyll-43a28aed967b/lib/jekyll/convertible.rb:65:in `transform'
	from /usr/local/bundle/bundler/gems/jekyll-43a28aed967b/lib/jekyll/convertible.rb:249:in `do_layout'
	from /usr/local/bundle/bundler/gems/jekyll-43a28aed967b/lib/jekyll/page.rb:122:in `render'
	from /usr/local/bundle/bundler/gems/jekyll-43a28aed967b/lib/jekyll/site.rb:302:in `block in render'
	from /usr/local/bundle/bundler/gems/jekyll-43a28aed967b/lib/jekyll/site.rb:301:in `each'
	from /usr/local/bundle/bundler/gems/jekyll-43a28aed967b/lib/jekyll/site.rb:301:in `render'
	from /usr/local/bundle/bundler/gems/jekyll-43a28aed967b/lib/jekyll/site.rb:55:in `process'
	from /usr/local/bundle/bundler/gems/jekyll-43a28aed967b/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/bundle/bundler/gems/jekyll-43a28aed967b/lib/jekyll/commands/build.rb:58:in `build'
	from /usr/local/bundle/bundler/gems/jekyll-43a28aed967b/lib/jekyll/commands/build.rb:34:in `process'
	from /usr/local/bundle/bundler/gems/jekyll-43a28aed967b/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /usr/local/bundle/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/local/bundle/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/bundler/gems/jekyll-43a28aed967b/bin/jekyll:20:in `<top (required)>'
	from /usr/local/bundle/bin/jekyll:16:in `load'
	from /usr/local/bundle/bin/jekyll:16:in `<main>'
rake aborted!
Command failed with status (1): [bundle exec jekyll build --trace...]
/www/Rakefile:295:in `jekyll'
/www/Rakefile:97:in `block in <top (required)>'
Tasks: TOP => build
(See full trace by running task with --trace)
```

**Comment by parkr** [comment]
Try adding this to your _config.yml

```yaml
encoding: utf-8
```

This character is [is â](http://www.codetable.net/hex/e2). Do you have any non-English characters in `assets/css/styles.scss` or any of its imports?

**Comment by dalanmiller** [comment]
Happened again with the `_config.yml` change. I `ack`'d through my repo and couldn't find any of those and don't see why I would have any non-English characters in the imports. Also, it says it's occurring here in the `styles.scss` file:

```
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/styles.scss':
                    Invalid US-ASCII character "\xE2" on line 3
/usr/local/bundle/gems/jekyll-sass-converter-1.3.0/lib/jekyll/converters/scss.rb:97:in `rescue in convert': Invalid US-ASCII character "\xE2" on line 3 (Jekyll::Converters::Scss::SyntaxError)
```

**assets/css/styles.scss**
```sass
---
---
@charset "utf-8";

// Bourbon, Neat, Bitters, Base styles
@import "normalize";
@import "bourbon";
@import "neat";
@import "base/base";
```

**Comment by dalanmiller** [comment]
Also hi @parkr! I ate lunch with you at Github Universe!

**Comment by dalanmiller** [comment]
For the record, [I found this great one-liner](https://stackoverflow.com/questions/3001177/how-do-i-grep-for-all-non-ascii-characters-in-unix#comment18815407_9395552) for finding non-ASCII characters:

```
# Linux
grep --color='auto' -P -n "[\x80-\xFF]" file.xml

# Mac OS X after brew install pcre
pcregrep --color='auto' -n "[\x80-\xFF]" file.xml
```

**Comment by pathawks** [comment]
If you comment out all the `@import`s in **assets/css/styles.scss** do you still get the same error message? If you comment out all but one, can you figure out which one is causing the error message?

**Comment by parkr** [comment]
Ok, so per [the Sass documentation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html):

> Sass follows the CSS spec to determine the encoding of a stylesheet, and falls back to the Ruby string encoding. This means that it first checks the Unicode byte order mark, then the @charset declaration, then the Ruby string encoding. If none of these are set, it will assume the document is in UTF-8.

So it should assume UTF-8, so this character should not be a problem. Interesting issue, this is. Line three would be the line which contains `// Bourbon, Neat, Bitters, Base styles`, which doesn't _appear_ to contain `\xE2`. Try @pathawks's solution for debugging this... this is super weird. If you can isolate a given line in your CSS through this method, that would help. We delegate imports entirely to Sass, so they should be able to slurp up everything as UTF-8 by default as specified.

**Comment by dalanmiller** [comment]
Nice to see a friendly face on the Internet now and again @parkr :+1: 

So just to follow up, I used that unicode character search and found just two lines where I could just replace them with ASCII equivalents. They were both comments anyway so nothing got hurt and I could build my Jekyll docker container. 

It'd probably be a lot more helpful for `jekyll/jekyll-sass-converter` to output the problems lines of the original source files as it traverses the import "tree" versus just the top most line where an `@import` occurs

**Comment by parkr** [comment]
> It'd probably be a lot more helpful for jekyll/jekyll-sass-converter to output the problems lines of the original source files as it traverses the import "tree" versus just the top most line where an @import occurs

It may be an issue in Sass itself, as [we output the line from the Sass error](https://github.com/jekyll/jekyll-sass-converter/blob/e8244e717d3489ae586c90f188611e92d9ffa0bb/lib/jekyll/converters/scss.rb#L96-L97). If Sass passed us back the line in the imported file, then that would help a bit more, of course. [Maybe `#sass_backtrace` would be more helpful?](http://sass-lang.com/documentation/Sass/SyntaxError.html#sass_backtrace-instance_method) If you have a few minutes, would be great to have you test out the output of that in your failure scenario.

**Comment by burntcookie90** [comment]
I'm seeing this issue when using octopress on one of my machines but not the other. Haven't been able to figure out which possible variable is causing the issue on the erroring machine.

**Comment by pathawks** [comment]
Can somebody post the source of a site? I would like to investigate this issue

**Comment by parkr** [comment]
I believe this issue is fixed in jekyll-sass-converter v1.4.0, which I just released. https://github.com/jekyll/jekyll-sass-converter/releases/tag/v1.4.0

**Comment by AngeloAballe** [comment]
I'm also having this issue. No problem if hosted via GitHub pages, but when I use docker on my own laptop or server, it has this issue.

The problem is the
---
---

above the scss file. If you remove this, there would be no error but the scss will not be converted. Still don't know how to fix this.

**Comment by parkr** [comment]
Did you upgrade your version of Jekyll-sass-converter?

**Comment by AngeloAballe** [comment]
[Imgur](http://i.imgur.com/VAhgYFR.png)

I tried. Same error.

**Comment by parkr** [comment]
@AngeloAballe The YAML front matter (two lines of `---`) are not the problem – they merely tell Jekyll to convert the SCSS into CSS. Have you tried outside of Docker? See [Dalan's comment](https://github.com/jekyll/jekyll/issues/4268#issuecomment-165617139) about finding these characters:

```bash
# Linux
grep --color='auto' -P -n "[\x80-\xFF]" file.xml

# Mac OS X after brew install pcre
pcregrep --color='auto' -n "[\x80-\xFF]" file.xml
```

**Comment by AngeloAballe** [comment]
Thanks for the reply @parkr but after searching, I manage to fix it and I'm sharing my solution. I found out that the docker container is using a different charset or locale so you have to set it in you docker file.

I manage to fix mine by adding this on my Dockerfile. No need to upgrade to sass converter 1.4.0.

```
# Install program to configure locales
RUN apt-get install -y locales
RUN dpkg-reconfigure locales && \
  locale-gen C.UTF-8 && \
  /usr/sbin/update-locale LANG=C.UTF-8

# Install needed default locale for Makefly
RUN echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen && \
  locale-gen

# Set default locale for the environment
ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
```

Hope this helps everyone!

**Comment by envygeeks** [comment]
hey @AngeloAballe if you are using the official Docker image can you push a ticket to https://github.com/jekyll/docker and we'll happily add that as a default, I didn't think Alpine lacked the default language vars (but I'm not surprised, it is an embedded OS.)

**Comment by mkyung** [comment]
Just for the future reference:

 I originally turned off `Set locale environment variables on startup` in my OSX Terminal preference due to other reasons. The error is gone if I check this checkbox.

**Comment by michaellee** [comment]
I ran into this issue as well while trying to build the site over at [GitLab](https://pages.gitlab.io/). What was causing the issue was this bit of code:

```
...
a::before{
  content:'“';
}
a::after{
  content:'”';
}
...
```

The `“` and `”` were the culprits. Changing them to be the hex value fixed the issue.

```
...
a::before{
  content:'\201C';
}
a::after{
  content:'\201D';
}
...
```

**Comment by simonorono** [comment]
I'm still getting this error on latest Jekyll. Check the CI log:

https://gitlab.com/simonorono/simonorono.gitlab.io/builds/2904606

**Comment by nateberkopec** [comment]
I get this problem when building a Jekyll site with `wercker` and there's Unicode in the SASS. Removing the UTF-8 characters  or using @AngeloAballe's solution works.

**Comment by MildTomato** [comment]
Hey guys!

I'm using Jekyll 3.3.0 and `wercker`. Getting a `Invalid US-ASCII character "\xE2" on line 15` on Wercker whenever it tries to build. 
Seems to be something in foundation-sites which is causing it, but can't find which file is causing the issue.
Only getting the invalid character issue on wercker, runs fine running locally.

**Comment by MildTomato** [comment]
OK, seemed to be a `—` in a foundation component which was the culprit.
Wercker runs fine now 😆

**Comment by Hwesta** [comment]
I also ran into this problem, and found this thread very helpful but it didn't cover my case.  Hopefully this helps the next person.

For me, setting `LANG=en_US.UTF-8` didn't work because the locale hadn't been generated on my system and it was falling back to `LANG=C` which caused the error.  Additionally, the problematic character I had was an en-dash (`\xe2\x80\x93`) not actually `â` (`\xe2`). The fix was to generate a UTF-8 locale and set it.  Instructions tested on Arch Linux.

1. Check if locale exists before you try to set it: `locale -a`
1. If not, generate locale: Uncomment locale name in `/etc/locale.gen` and run `sudo locale-gen`
1. Set locale for the system: Edit `/etc/locale.conf` and log in again for it to take effect
1. Or set locale for the terminal
   * bash: `export LANG=en_US.UTF-8`
   * fish: `set -xg LANG en_US.UTF-8`

**Comment by dltj** [comment]
My jekyll build is being done by AWS CodeBuild, and I found I needed to add these lines to the `buildspec.yml` file:

```yaml
  pre_build:
    commands:
      - export LC_ALL="C.UTF-8"
      - export LANG="en_US.UTF-8"
      - export LANGUAGE="en_US.UTF-8"

```

**Comment by IotaSpencer** [comment]
If anyone is getting this on GitLab, add the list on the above ^ 
https://github.com/jekyll/jekyll/issues/4268#issuecomment-357095209

just put this in a `before_script:` before everything else

**Comment by justinechacko** [comment]
I get this error in gitlab, @IotaSpencer  Where to add the code. I dont find buildspec.yml file

**Comment by reardestani** [comment]
For Jekyll on Gitlab, alternative to @IotaSpencer's solution is adding them in variables, like:

```
variables:
  LC_ALL: "C.UTF-8"
  LANG: en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"
```

**Comment by npeirson** [comment]
Solution above looks good, I also got around it by putting an env assignment in my rake file.

**Comment by stragu** [comment]
If anyone on GitLab Pages is wondering why @reardestani 's [solution](https://github.com/jekyll/jekyll/issues/4268#issuecomment-377681274) does not work, there is a typo (a missing `"`). It should be:

```
variables:
  LC_ALL: "C.UTF-8"
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"
```

Thanks everyone, I added those variables to my `.gitlab-ci.yml` file and it fixed it (and looked rather clean) :)
