### ISSUE TITLE
Release v3.8.6

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#7726]
We have a bunch of backported PR's merged to the 3.8-stable branch that should be released.

I updated [the History.markdown file on that branch](https://github.com/jekyll/jekyll/commit/47b67f1222768c7d8dce0b84e6402ee4ca1a7c78). Is there anything I'm missing?

/cc @ashmaroli @jekyll/core

**Comment by ashmaroli** [comment]
Awesome! Its finally happening..!! A release !
@parkr There's on final patch awaiting review and subsequent backport: #7679

**Comment by parkr** [comment]
Backported via https://github.com/jekyll/jekyll/pull/7734.

Did I miss anything in the History.markdown file? Any PR's we merged to this branch that haven't yet been released?

**Comment by ashmaroli** [comment]
@parkr Looks good to me. All the backport PRs that've been merged are registered in the History document.
All that's left is a PR for the release post. (I'll let you do the honors :stuck_out_tongue:)

**Comment by parkr** [comment]
Release notes: https://github.com/jekyll/jekyll/pull/7735

**Comment by breun** [comment]
I read on https://jekyllrb.com/news/2019/07/02/jekyll-3-8-6-released/ that Jekyll 3.8.6 has been released, but he latest Docker image at https://hub.docker.com/r/jekyll/jekyll/tags is still 3.8.5.

Also the top-right corner of https://jekyllrb.com still shows V3.8.5.

**Comment by ashmaroli** [comment]
@breun Thank you for reporting. I've updated the version in the header for `jekyllrb.com`. However, I don't have the authority to push a docker image.

**Comment by breun** [comment]
https://hub.docker.com/r/jekyll/jekyll points to https://github.com/jekyll/docker/tree/master/README.md which looks like a repository here, but redirects to https://github.com/envygeeks/jekyll-docker/blob/master/README.md which is part of another GitHub account.

I’ve created an issue there: https://github.com/envygeeks/jekyll-docker/issues/248

**Comment by ashmaroli** [comment]
Thanks once again. Jordon was a maintainer of this project once upon a time.

**Comment by parkr** [comment]
Released to RubyGems.
